CREATE TABLE IF NOT EXISTS L1_BRANCH (
    BRANCH_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    BRANCH_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS L1_TEACHERS (
    BRANCH_ID VARCHAR(20) NOT NULL,
    T_ID VARCHAR(30) NOT NULL PRIMARY KEY,
    T_NAME VARCHAR(50) NOT NULL,
    T_AGE INT NOT NULL,
    T_ROLE VARCHAR(50) NOT NULL,
    CONSTRAINT FK_BRANCH_ID_TEACHERS FOREIGN KEY (BRANCH_ID) REFERENCES L1_BRANCH (BRANCH_ID)
);

CREATE TABLE IF NOT EXISTS L1_SUBJECT_DETAILS (
    SUBJECT_CODE VARCHAR(20) NOT NULL PRIMARY KEY,
    SUBJECT_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS L1_SUBJECTS (
    SUBJECT_ID VARCHAR(20) NOT NULL PRIMARY KEY,
    BRANCH_ID VARCHAR(20) NOT NULL,
    SUBJECT_CODE VARCHAR(20) NOT NULL,
    T_INCHARGE_ID VARCHAR(30) NOT NULL,
    TOTAL_CLASS INT NOT NULL DEFAULT 0,
    CONSTRAINT FK_BRANCH_ID_SUBJECTS FOREIGN KEY (BRANCH_ID) REFERENCES L1_BRANCH (BRANCH_ID),
    CONSTRAINT FK_T_INCHARGE_ID_SUBJECTS FOREIGN KEY (T_INCHARGE_ID) REFERENCES L1_TEACHERS (T_ID),
    CONSTRAINT FK_SUBJECT_CODE_SUBJECTS FOREIGN KEY (SUBJECT_CODE) REFERENCES L1_SUBJECT_DETAILS (SUBJECT_CODE),
    UNIQUE (BRANCH_ID, T_INCHARGE_ID, SUBJECT_CODE)
);

CREATE TABLE IF NOT EXISTS L1_STUDENTS (
    USN VARCHAR(30) NOT NULL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    SEM INT NOT NULL,
    SECTION VARCHAR(5) NOT NULL,
    AGE INT NOT NULL,
    BRANCH_ID VARCHAR(20) NOT NULL,
    GENDER VARCHAR(10) NOT NULL,
    FATHER_NAME VARCHAR(50),
    MOTHER_NAME VARCHAR(50),
    ADDRESS VARCHAR(100),
    CONSTRAINT FK_BRANCH_ID_STUDENTS FOREIGN KEY (BRANCH_ID) REFERENCES L1_BRANCH (BRANCH_ID)
);

-- Can add extra column like phone_no, DOB etc.
CREATE TABLE IF NOT EXISTS L1_EMAIL_TO_USN (
    EMAIL_ID VARCHAR(50) NOT NULL PRIMARY KEY,
    USN VARCHAR(30) NOT NULL,
    CONSTRAINT FK_USN_EMAIL FOREIGN KEY (USN) REFERENCES L1_STUDENTS (USN)
);

CREATE TABLE IF NOT EXISTS L1_CLASSES (
    CLASS_ID SERIAL PRIMARY KEY,
    CLASS_NO INT NOT NULL,
    SUBJECT_ID VARCHAR(20) NOT NULL,
    DATE DATE NOT NULL,
    TIME TIME NOT NULL,
    CONSTRAINT FK_SUBJECT_ID_ATTEND FOREIGN KEY (SUBJECT_ID) REFERENCES L1_SUBJECTS (SUBJECT_ID),
    UNIQUE (CLASS_NO, SUBJECT_ID),
    UNIQUE (SUBJECT_ID, DATE, TIME)
);

CREATE TABLE IF NOT EXISTS L1_STUDENTS_ATTEND (
    CLASS_ID INT NOT NULL,
    USN VARCHAR(30) NOT NULL,
    ATTENDANCE BOOLEAN NOT NULL,
    CONSTRAINT FK_USN_ATTEND FOREIGN KEY (USN) REFERENCES L1_STUDENTS (USN),
    CONSTRAINT FK_CLASS_ID_ATTEND FOREIGN KEY (CLASS_ID) REFERENCES L1_CLASSES (CLASS_ID),
    PRIMARY KEY (CLASS_ID, USN)
);

CREATE TABLE IF NOT EXISTS L1_TESTS (
    TEST_ID SERIAL PRIMARY KEY,
    TEST_CODE VARCHAR(20) NOT NULL,
    SUBJECT_ID VARCHAR(20) NOT NULL,
    DATE DATE NOT NULL,
    TIME TIME NOT NULL,
    TOTAL_MARKS NUMERIC(10, 2) NOT NULL DEFAULT 0,
    CONSTRAINT FK_SUBJECT_ID_TESTS FOREIGN KEY (SUBJECT_ID) REFERENCES L1_SUBJECTS (SUBJECT_ID),
    UNIQUE (TEST_CODE, SUBJECT_ID),
    UNIQUE (SUBJECT_ID, DATE, TIME)
);

CREATE TABLE IF NOT EXISTS L1_STUDENTS_MARKS (
    TEST_ID INT,
    USN VARCHAR(30) NOT NULL,
    MARKS NUMERIC(10, 2) NOT NULL,
    CONSTRAINT FK_USN_MARKS FOREIGN KEY (USN) REFERENCES L1_STUDENTS (USN),
    CONSTRAINT FK_TEST_ID_MARKS FOREIGN KEY (TEST_ID) REFERENCES L1_TESTS (TEST_ID),
    PRIMARY KEY (TEST_ID, USN)
);

CREATE TABLE IF NOT EXISTS L1_ANNOUNCEMENT (
    ANNOUNCEMENT_ID SERIAL PRIMARY KEY,
    BRANCH_ID VARCHAR(20) NOT NULL DEFAULT 'all',
    ANNOUNCEMENT_MESSAGE TEXT NOT NULL,
    DATE DATE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    TIME TIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_BRANCH_ID_ANNOUNCEMENT FOREIGN KEY (BRANCH_ID) REFERENCES L1_BRANCH (BRANCH_ID)
);