SELECT
    SA.CLASS_ID,
    SA.USN,
    SA.ATTENDANCE,
    LC.CLASS_NO,
    LC.SUBJECT_ID,
    LC.DATE,
    LC.TIME,
    LS.SUBJECT_CODE,
    LSD.SUBJECT_NAME
FROM
    L2_STUDENTS_ATTEND SA
    LEFT JOIN L2_CLASSES LC
    ON SA.CLASS_ID = LC.CLASS_ID
    LEFT JOIN L2_SUBJECTS LS
    ON LS.SUBJECT_ID = LC.SUBJECT_ID
    LEFT JOIN L2_SUBJECT_DETAILS LSD
    ON LS.SUBJECT_CODE = LSD.SUBJECT_CODE
WHERE
    SA.USN = '1MP22CS031'
ORDER BY
    LC.SUBJECT_ID,
    LC.CLASS_NO;